### ISSUE TITLE
Disable ability to use 3rd party devise-modules (i.e. devise_invitable)

### ISSUE THREAD

**Issue by vladimir-shidlovsky** [spree-contrib/spree_social#143]
When I tried to use [devise_invitable](https://github.com/scambra/devise_invitable) in one application with [spree_social](https://github.com/spree-contrib/spree_social) and [spree_auth_devise](https://github.com/spree/spree_auth_devise) I got following exception:
```
.../gems/actionpack-4.1.6/lib/action_dispatch/routing/route_set.rb:430:in `add_route': Invalid route name, already in use: 'accept_spree_user_invitation'  (ArgumentError)
You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with `resources` as explained here: 
```
The reason of the issue is double adding device_invitable route by double calling of "device_for" method:
1. First time in spree_auth_devise/config/routes.rb
2. Second time in spree_social/config/routes.rb

To resolve issues like mentioned above devise_for method supports following options :skip and :only. The current implementation is using :skip option. But in my opinion :only option is more correct to be used as we can't know which 3rd party devise-modules developers will use.

**Comment by futhr** [comment]
Been fixed with #144
