### ISSUE TITLE
git://github.com/spree/spree.git (at 2-4-stable) is not yet checked out error after bundle install

### ISSUE THREAD

**Issue by thiyagarajan** [spree-contrib/spree_social#147]
Hi,

1. added spree 2.4
2. added spree_social 2.4
3. bundle install

then
$ bundle exec rails g spree_social:install
DL is deprecated, please use Fiddle
DL is deprecated, please use Fiddle
      insert  vendor/assets/stylesheets/spree/frontend/all.css
         run  bundle exec rake railties:install:migrations FROM=spree_social fro
m "."
git://github.com/spree/spree.git (at 2-4-stable) is not yet checked out. Run `bu
ndle install` first.
Would you like to run the migrations now? [Y/n]

Why getting git://github.com/spree/spree.git (at 2-4-stable) is not yet checked out. Run `bu
ndle install` first.

Thanks
Thiyagarajan Veluchamy

**Comment by chidea** [comment]
This happened when the nodejs was not installed.

**Comment by futhr** [comment]
Noticed this error with latest spring v1.3.0

**Comment by futhr** [comment]
Closing this issue due to its not related to the gem itself.
