### ISSUE TITLE
Spree_social breaks confirmation email url.

### ISSUE THREAD

**Issue by unikoid** [spree-contrib/spree_social#150]
I have enabled `:confirmable` in my spree_auth_devise configuration.
After I have installed spree_social, links sent in confirmation email became invalid. They point to /users/confirmation instead of /user/spree_user/confirmation.
This can be fixed adding `:confirmations` to the `:skip` section of `devise_for` in `routes.rb`. 
Please, fix it!

**Comment by JDutil** [comment]
Please submit a PR with your suggested fix.

**Comment by futhr** [comment]
Think it fixed with this 169e2c4c6b80844b219dc888423fddb02fd2dab1 in `master` branch.

**Comment by futhr** [comment]
@unikoid it has now also been applied to `2-4-stable` branch. 

There are many commits in `2-4-stable` and `master` that you easy can `git cherry-pick` to patch your desired branch if you use a lower version. Then when you get everything working (with passing specs) you can just submit a PR with the commits and we will merge it. 

Its open source so we encourage everyone that use it to help out the way they can.

Happy coding!

**Comment by unikoid** [comment]
Thanks a lot for the fix and for tip about `cherry-pick`. Haven't heard about this before.
