### ISSUE TITLE
What about 3-0-stable branch?

### ISSUE THREAD

**Issue by romul** [spree-contrib/spree_social#152]

**Comment by JDutil** [comment]
You should have commit access to make one, but please make sure specs are passing before creating a "stable" branch.

**Comment by romul** [comment]
Yes, but I've asked, b/c maybe you have some reasons, why it was skipped before updating master to 3.1

**Comment by JDutil** [comment]
I'm not maintaining this extension so I'm not really sure why it was skipped over.  Probably was just overlooked.

**Comment by futhr** [comment]
@romul There was some confusing dependency issues for 3-0-stable branch so I skipped creating that branch. I can probably fix that now, think its just 3 commits that do not apply.

**Comment by futhr** [comment]
Create `3-0-stable` branch now, seems like all commits applied except from 80e95a7ed30dc320849a2e376cf5402360294bb7
