### ISSUE TITLE
spree_social version compatibility with spree of spree_core

### ISSUE THREAD

**Issue by hiteshkanwar** [spree-contrib/spree_social#153]
My Gemfile have these working spree : 
gem 'spree', github: 'edgward/spree', branch: '2-4-stable-locked'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '2-4-stable'
gem 'spree_auth_devise', :git => 'https://github.com/spree/spree_auth_devise.git', :branch => '2-4-stable'
gem 'spree_volume_pricing', github: 'spree-contrib/spree_volume_pricing', branch: 'master'
gem 'spree_reuse_credit_card', github: 'edgward/spree_reuse_credit_card', branch: 'master'

But when I add the gem : 
gem 'spree_social', github: 'spree-contrib/spree_social', :branch => "2-4-stable"

It gives me below error : 

Bundler could not find compatible versions for gem "spree_core":
  In Gemfile:
    spree_social (>= 0) ruby depends on
      spree_core (~> 2.4.0) ruby

    spree (>= 0) ruby depends on
      spree_core (2.4.0.rc4)

I don't find any spree_social branch which depends on spree_core (2.4.0.rc4)

**Comment by JDutil** [comment]
Have you tried: `bundle update spree_social` or `bundle update spree`
