### ISSUE TITLE
undefined method `to_url' for "google_oauth2":String

### ISSUE THREAD

**Issue by shaliniOD** [spree-contrib/spree_social#156]
Hello,

Spree social is giving me undefined method error when I try to go to Login or Signup page.
Here are the version details of gems:
gem 'omniauth-linkedin'
gem 'spree', '3.0.0'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '3-0-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '3-0-stable'
gem 'spree_social', github: 'spree-contrib/spree_social', branch: '3-0-stable'

**Comment by ckk-scratch** [comment]
After a bit of digging I could not find the source of this method call. Its apparently just trying to create a URL friendly slug..  I'm customizing all my views so ill probably just get rid of it.. but you can add a file in your initializer that will accomplish that. 

'''
class String
  def to_url
  	self.downcase.gsub!(" ","-")
  end
end
'''

**Comment by abhijain21** [comment]
This is still an issue. I'm on spree 3.0 and rails 4.

**Comment by ronaldoooo** [comment]
+1， still an issue。 Using spree 3.2 with spree social 3.2.0.alpha

**Comment by damianlegawiec** [comment]
@ronaldoooo please update to latest master, it contains a fix for this
