### ISSUE TITLE
This app is still in development mode, and you don't have access to it.

### ISSUE THREAD

**Issue by Ionut-Milas** [spree-contrib/spree_social#158]
Hi guys.

I try to test Facebook login but i keep getting this error when testing ether on staging or locally.

I have an staging set-up here: http://89.34.92.115/

I added to the Facebook's app Site URL a lot of variation: the ip of the staging, localhost.local:3000, my_ip:local:3000 but every time I keep hitting that message...

Any help ?

The complete message:

Your app is not configured. This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.

**Comment by thecodersblock** [comment]
in 'App Review' Tab : change

Do you want to make this app and all its live features available to the general public? Yes
