### ISSUE TITLE
Facebook login problem Invalid Scopes: offline_access. 

### ISSUE THREAD

**Issue by Godweed** [spree-contrib/spree_social#162]
gem 'spree_social', github: 'spree-contrib/spree_social', branch: '3-0-stable'
Facebook authentication giving Invalid Scopes: offline_access error, 

Invalid Scopes: offline_access. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

**Comment by avilunin** [comment]
The same issue on the 2.4 branch.

**Comment by futhr** [comment]
Resolved with d5e5efb172665860692ddf534be84055eccd01df and 4b2bfb4deeb1dc17cd0ee5f46b0441af786687c1

**Comment by hnatt** [comment]
@futhr can we have it fixed on 2-3-stable?
