### ISSUE TITLE
could not add gem to Gemfile in spree 3.0.4

### ISSUE THREAD

**Issue by lmahendra** [spree-contrib/spree_social#166]
Hi, I was unable to add this gem to spree 3.0.4 it's throwing following dependency error

    Bundler could not find compatible versions for gem "spree_core":
      In snapshot (Gemfile.lock):
        spree_core (= 3.0.4)

      In Gemfile:
        spree_core (= 3.0.4) ruby

    spree_core (~> 3.0.0) ruby

    spree_core (~> 3.0.0) ruby

    spree_social (>= 0) ruby depends on
      spree_core (~> 3.1.0.beta) ruby

    Running `bundle update` will rebuild your snapshot from scratch, using only
    the gems in your Gemfile, which may resolve the conflict.

please help me resolve the issue.

**Comment by CucumisSativus** [comment]
Can you show your gemfile please? My blind shot is that you have spree from brach 3-0-stable and spree social auth from branch master

**Comment by damianlegawiec** [comment]
@lmahendra change your Gemfile to
