### ISSUE TITLE
problem with devise :omniauthable

### ISSUE THREAD

**Issue by eniwito** [spree-contrib/spree_social#193]
Hi!
I use ruby 2.4.0, rails 5, spree 3.2 and install spree_social from master branch.
I try start rails server and get error: 
```
Mapping omniauth_callbacks on a resource that is not omniauthable
Please add `devise :omniauthable` to the `Spree::User` model (ArgumentError)
```

why? spree_social have devise :omniauthable (user_decorator.rb)

**Comment by symarys** [comment]
@eniwito I'm trying to reproduce your issue with the same gem versions, but I don't see any errors. Could you provide more details, based on the questions below?

## Steps to Reproduce


1.
2.
3.
4.

## Your Environment

* Version used:
* Gemfile and Gemfile.lock as text in a Gist:
* Any relevant stack traces ("Full trace" preferred):

**Comment by eniwito** [comment]
I use:
rails 5.0.2, ruby 2.4.0

1. start create new app with: rails new spree_test
2. create db with: rails db:create
3. i add to gem file this lines:
```
# Spree
gem 'spree', '~> 3.2.0'
gem 'spree_auth_devise', '~> 3.2.0.beta'
gem 'spree_gateway', '~> 3.2.0.beta'
gem 'spree_social', github: 'spree-contrib/spree_social'
```
_Screenshot: http://prntscr.com/emnezf_

4. I try install spree with command:
rails g spree:install --user_class=Spree::User
this command work good
after i try install spree_auth with command: rails g spree:auth:install 
and get error:
```
Mapping omniauth_callbacks on a resource that is not omniauthable
Please add `devise :omniauthable` to the `Spree::User` model (ArgumentError)
```
_Screenshot: http://prntscr.com/emng8y_

**Comment by eniwito** [comment]
if remove from gemfile: gem 'spree_social', github: 'spree-contrib/spree_social' 
installed good, but if install spree_social after spree any change in the code (another file in rails app - controller, model, locales) will cause an error when updating the application in the background

**Comment by eniwito** [comment]
in rails 4.2 ruby 2.3.3, install with this steps works good

**Comment by symarys** [comment]
Thank you for the details, I can reproduce your issue now. I'll try to figure out what's happening there. For the time being - adding `bundle exec` in front of your commands (e.g. `bundle exec rails g model YourModel`) should help.

**Comment by symarys** [comment]
@eniwito Ok, I believe this issue is not connected to Spree itself, but to gem Spring, in particular this issue: https://github.com/rails/spring/issues/486
In my case running `spring stop` before my commands helps - I no longer see the omniauthable error.

**Comment by eniwito** [comment]
@symarys ok, thanks for your view. But this error makes the work uncomfortable with this gem in dev environment.

**Comment by nemofang** [comment]
For anyone who comes her for solution:
This is a issue due to rails 5 reload order change from the discussion of solidus_social gem, this is the link: https://github.com/solidusio-contrib/solidus_social/issues/20. 

I tried the solution from this discussion, so far so good. Tried couple of times, didn't see the issue any more.
